import type { NextPage } from "next";
import Head from "next/head";
import MyListbox from "../components/MyListbox";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-center">
        <div className="mt-0 h-20 w-96 mx-auto">
          <MyListbox />
        </div>
        <div className="mt-2 h-20 w-96 mx-auto">
          <MyListbox />
        </div>
      </div>

      <footer></footer>
    </div>
  );
};

export default Home;
